# Training configuration for ResNet trained on ImageNet on TPUs.
# Takes ~4 minutes, 30 seconds seconds per epoch for a v3-32.
# Reaches > 76.1% within 90 epochs.
# Note: This configuration uses a scaled per-replica batch size based on the number of devices.
runtime:
  distribution_strategy: 'tpu'
train_dataset:
  name: 'cifar10'
  data_dir: null
  builder: 'records'
  split: 'train'
  one_hot: false
  image_size: 32
  num_classes: 10
  num_examples: 50000
  batch_size: 64
  use_per_replica_batch_size: true
  mean_subtract: false
  standardize: false
  dtype: 'bfloat16'
  filenames: ['cifar10-train.tfrecord-00000-of-00001']
validation_dataset:
  name: 'cifar10'
  data_dir: null
  builder: 'records'
  split: 'validation'
  one_hot: false
  image_size: 32
  num_classes: 10
  num_examples: 10000
  batch_size: 64
  use_per_replica_batch_size: true
  mean_subtract: false
  standardize: false
  dtype: 'bfloat16'
  filenames: ['cifar10-test.tfrecord-00000-of-00001']
model:
  name: 'resnet'
  num_classes: 10
  model_params:
    rescale_inputs: true
    num_classes: 10
    image_size: 32
  optimizer:
    name: 'momentum'
    momentum: 0.9
    decay: 0.9
    epsilon: 0.001
    moving_average_decay: 0.
    lookahead: false
  loss:
    label_smoothing: 0.1
train:
  callbacks:
    enable_checkpoint_and_export: true
  resume_checkpoint: true
  epochs: 6
evaluation:
  epochs_between_evals: 1
